WorldDatabase/Models/City.cs
namespace WorldDatabase.Models
{
    public class City
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int State_id { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }

        public virtual State State { get; set; }
    }
}

WorldDatabase/Models/Country.cs
namespace WorldDatabase.Models
{

    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Iso3 { get; set; }
        public string Iso2 { get; set; }
        public string Numeric_code { get; set; }
        public string Phone_code { get; set; }
        public string Capital { get; set; }
        public string Currency { get; set; }
        public string Currency_name { get; set; }
        public string Currency_symbol { get; set; }
        public string Tld { get; set; }
        public string Native { get; set; }
        public string Region { get; set; }
        public string Subregion { get; set; }
        public string Nationality { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Emoji { get; set; }
        public string EmojiU { get; set; }
        
        public virtual Translation Translations { get; set; }
        public virtual List<State> States { get; set; }
        public virtual List<Timezone> Timezones { get; set; }
    }
}

WorldDatabase/Models/ErrorViewModel.cs
namespace WorldDatabase.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WorldDatabase/Models/State.cs
namespace WorldDatabase.Models
{
    public class State
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Country_id { get; set; }
        public string State_code { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }

        public virtual Country Country { get; set; }
        public virtual List<City> Cities { get; set; }
    }
}

WorldDatabase/Models/Timezone.cs
namespace WorldDatabase.Models
{
    public class Timezone
    {
        public int Id { get; set; }
        public string ZoneName { get; set; }
        public int GmtOffset { get; set; }
        public string GmtOffsetName { get; set; }
        public string Abbreviation { get; set; }
        public string TzName { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
    }
}

WorldDatabase/Models/Translation.cs
namespace WorldDatabase.Models
{
    public class Translation
    {
        public int Id { get; set; }
        public string Kr { get; set; }
        public string PtBR { get; set; }
        public string Pt { get; set; }
        public string Nl { get; set; }
        public string Hr { get; set; }
        public string Fa { get; set; }
        public string De { get; set; }
        public string Es { get; set; }
        public string Fr { get; set; }
        public string Ja { get; set; }
        public string It { get; set; }
        public string Cn { get; set; }
        public string Tr { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
    }
}

WorldDatabase/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WorldDatabase.Data;
using WorldDatabase.Models;
using Microsoft.EntityFrameworkCore;

namespace WorldDatabase.Controllers
{
    public class CountriesController : Controller
    {
        private readonly DatabaseContext db;

        public CountriesController(DatabaseContext db) => this.db = db;

        public IActionResult Index()
        {
            List<Country> countryList = db.Countries.ToList();
            return View(countryList);
        }

        [HttpGet("{id}")]
        public IActionResult Details(int id)
        {
            Country country = db.Countries.Include(c => c.Translations).Include(c => c.States).ThenInclude(c => c.Cities)
                .FirstOrDefault(c => c.Id == id);
            return View(country);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WorldDatabase/Views/Countries/Details.cshtml
@model Country
@{
    ViewData["Title"] = $"{Model.Name} ({Model.Native})";
}

<h1><a href="/" class="btn btn-dark">Back</a> @ViewData["Title"] <img style="height:2.5rem;" src="~/img/CountriesFlags/@(Model.Iso3).svg" asp-append-version="true" /></h1>

<div class="table-responsive">
    <h2>Details</h2>
    <table class="table">
        <tr>
            <th class="table-primary">Name</th>
            <td>@Model.Name</td>
            <th class="table-primary">Native</th>
            <td>@Model.Native</td>
            <th class="table-primary">ISO 2</th>
            <td>@Model.Iso2</td>
            <th class="table-primary">ISO 3</th>
            <td>@Model.Iso3</td>
        </tr>
        <tr>
            <th class="table-primary">Phone Code</th>
            <td>@Model.Phone_code</td>
            <th class="table-primary">Currency</th>
            <td>@Model.Currency_name (@Model.Currency | @Model.Currency_symbol)</td>
            <th class="table-primary">Capital</th>
            <td>@Model.Capital</td>
            <th class="table-primary">Nationality</th>
            <td>@Model.Nationality</td>
        </tr>
    </table>
    <h2>Translations</h2>
    <table class="table">
        <tr>
            <th class="table-primary">KR</th>
            <td>@Model.Translations?.Kr</td>
            <th class="table-primary">PT</th>
            <td>@Model.Translations?.Pt</td>
            <th class="table-primary">NL</th>
            <td>@Model.Translations?.Nl</td>
            <th class="table-primary">SE</th>
            <td>@Model.Translations?.Es</td>
        </tr>
        <tr>
            <th class="table-primary">HR</th>
            <td>@Model.Translations?.Hr</td>
            <th class="table-primary">FA</th>
            <td>@Model.Translations?.Fa</td>
            <th class="table-primary">DE</th>
            <td>@Model.Translations?.De</td>
            <th class="table-primary">FR</th>
            <td>@Model.Translations?.Fr</td>
        </tr>
        <tr>
            <th class="table-primary">JA</th>
            <td>@Model.Translations?.Ja</td>
            <th class="table-primary">IT</th>
            <td>@Model.Translations?.It</td>
            <th class="table-primary">CN</th>
            <td>@Model.Translations?.Cn</td>
            <th class="table-primary">TR</th>
            <td>@Model.Translations?.Tr</td>
        </tr>
    </table>
    <h2>Location</h2>
    <table class="table">
        <tr>
            <th class="table-primary">Region</th>
            <td>@Model.Region</td>
            <th class="table-primary">Subregion</th>
            <td>@Model.Subregion</td>
        </tr>
    </table>
    <iframe style="width:100%"
            height="500"
            frameborder="0"
            scrolling="yes"
            marginheight="0"
            marginwidth="0"
            src="https://maps.google.com/maps?q=@Model.Latitude,@Model.Longitude&hl=es&z=6&amp;output=embed">
    </iframe>
    <h2>States/Cities</h2>
    <ul>
        @foreach (State state in Model.States)
        {
            <li>
                @state.Name (@state.State_code) <a href="https://www.google.com/maps/@@@state.Latitude,@state.Longitude,9z?entry=ttu" target="_blank">Location</a>
                <ul>
                    @foreach (City city in state.Cities)
                    {
                        <li>@city.Name <a href="https://www.google.com/maps/@@@city.Latitude,@city.Longitude,14z?entry=ttu" target="_blank">Location</a></li>
                    }
                </ul>
            </li>
        }
    </ul>
</div>

WorldDatabase/Views/Countries/Index.cshtml
@model IEnumerable<Country>
@{
    ViewData["Title"] = $"World Countries ({Model.Count()})";
}
<h1>@ViewData["Title"]</h1>
<div class="table-responsive">
    <table class="table table-hover table-striped align-middle">
        <thead>
            <tr>
                <th>Country</th>
                <th>ISO</th>
                <th>Phone Code</th>
                <th>Currency</th>
                <th>Capital</th>
                <th>Location</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Country country in Model)
            {
                <tr>
                    <td>@country.Name (@country.Native)</td>
                    <td>@country.Iso2 | @country.Iso3</td>
                    <td>@country.Phone_code</td>
                    <td>@country.Currency</td>
                    <td>@country.Capital</td>
                    <td><a class="btn btn-dark" href="https://www.google.com/maps/@@@country.Latitude,@country.Longitude,6z?entry=ttu" target="_blank">Go</a></td>
                    <td><a class="btn btn-primary" href="/@country.Id">More</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

WorldDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - World Database</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorldDatabase.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Countries" asp-action="Index">World Database</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Home</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - <a href="https://walid-moheyeldin.azurewebsites.net/" target="_blank">Walid Moheyeldin</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>